### ISSUE TITLE
Paper fork 1.16.3 error.

### ISSUE THREAD

**Issue by KoxSosen** [EmirKutluay/AwesomeChallenges#1]
[16:38:06 ERROR]: Could not pass event EntityDeathEvent to AwesomeChallenges v1.2
java.lang.NullPointerException: null
        at com.emiv.awesomechallenges.onKill.onKillEvent(onKill.java:34) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor31.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Purpur-801]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Purpur-801]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Purpur-801]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Purpur-801]
        at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:813) ~[patched_1.16.3.jar:git-Purpur-801]
        at net.minecraft.server.v1_16_R2.EntityLiving.d(EntityLiving.java:1514) ~[patched_1.16.3.jar:git-Purpur-801]
        at net.minecraft.server.v1_16_R2.EntityLiving.die(EntityLiving.java:1441) ~[patched_1.16.3.jar:git-Purpur-801]
        at net.minecraft.server.v1_16_R2.EntityLiving.damageEntity(EntityLiving.java:1270) ~[patched_1.16.3.jar:git-Purpur-801]
        at net.minecraft.server.v1_16_R2.EntityInsentient.damageEntity(EntityInsentient.java:275) ~[patched_1.16.3.jar:git-Purpur-801]
        at net.minecraft.server.v1_16_R2.EntityLiving.entityBaseTick(EntityLiving.java:273) ~[patched_1.16.3.jar:git-Purpur-801]
        at net.minecraft.server.v1_16_R2.EntityInsentient.entityBaseTick(EntityInsentient.java:244) ~[patched_1.16.3.jar:git-Purpur-801]
        at net.minecraft.server.v1_16_R2.Entity.tick(Entity.java:455) ~[patched_1.16.3.jar:git-Purpur-801]
        at net.minecraft.server.v1_16_R2.EntityLiving.tick(EntityLiving.java:2455) ~[patched_1.16.3.jar:git-Purpur-801]
        at net.minecraft.server.v1_16_R2.EntityInsentient.tick(EntityInsentient.java:332) ~[patched_1.16.3.jar:git-Purpur-801]
        at net.minecraft.server.v1_16_R2.WorldServer.entityJoinedWorld(WorldServer.java:1322) ~[patched_1.16.3.jar:git-Purpur-801]
        at net.minecraft.server.v1_16_R2.World.a(World.java:900) ~[patched_1.16.3.jar:git-Purpur-801]
        at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:961) ~[patched_1.16.3.jar:git-Purpur-801]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1429) ~[patched_1.16.3.jar:git-Purpur-801]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:381) ~[patched_1.16.3.jar:git-Purpur-801]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1280) ~[patched_1.16.3.jar:git-Purpur-801]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1006) ~[patched_1.16.3.jar:git-Purpur-801]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.3.jar:git-Purpur-801]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]

**Comment by EmirKutluay** [comment]
I think you get this error because you put a wrong entity type in a kill challenge. You can check entity types from here https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
You need to make sure that the entity you choose have a EntityDeathEvent
